<section>            
            <div class="container">
                <h1 id="social">Estudios Sociales</h1><hr>
                <div class="row">
                    <img src="https://goo.gl/SMVnXe" class="col-md-3"></img>
                    <p class="col-md-9">
                        A medida que las personas son más conscientes de sus identidades ‘online’, y a medida que aumenta el tiempo que dedican a las redes sociales, cada vez son más los estudios que quieren estudiar los impactos de las redes sociales en los usuarios. Algunas investigaciones han señalado que las redes sociales podrían estar relacionados con baja autoestima y depresión en adolescentes. Sin embargo esta vez se tratan otras variantes.<br><br>
                        Las amistades y otras relaciones ‘offline’ se han asociado en muchos estudios con longevidad, pero las interacciones online podrían tener propiedades distintas. En el estudio se referenciaron 12 millones de perfiles de Facebook con los récords de salud del Departamento de Salud Pública de California, y se usaron modelos estadísticos para descubrir si el uso de redes sociales está asociado con una vida más larga.<br><br>
                        Los resultados mostraron que recibir solicitudes para conectarse como amigos ‘online’ está asociado con menor mortalidad, pero iniciar amistades no. Adicionalmente, los comportamientos online que indican actividades en la vida real, como publicar fotos, están asociados con menos riesgo de mortalidad. En cambio otros comportamientos, como enviar mensajes por chats, tienen una relación menos directa: su uso moderado está asociado con menor mortalidad.<br><br>
                        Los investigadores de la Universidad de California, autores del estudio, aclararon que los descubrimientos no son de correlación sino de asociación, es decir que no se puede decir que haya una causa y efecto demostrados, explicó TechTimes. Aunque este es solo un estudio de asociación, puede ser un paso importante para entender cómo las redes sociales se pueden adaptar para mejorar la salud social y física de las personas, dice el estudio.<br><br>
                        Los autores líderes, William Hobbs y James Fowler, explican que lo que busca el estudio es probar que las personas que ejercen y mantienen interacciones sociales por más tiempo tienen más probabilidades de vivir más años que aquellos que no. Por primera vez en la historia, un estudio correlaciona el comportamiento online con mantener círculos sociales en la vida real.<br><br>
                        Los resultados sugieren que por lo general hay menor riesgo de desarrollar ciertas enfermedades en las personas que usan redes sociales moderadamente. “Interactuar ‘online’ parece ser saludable cuando las actividades ‘online’ son moderadas y complementan las interacciones ‘offline’”, explica Hobbs.<br><br>
                    </p>
                </div>
        </section>